spring:
  #  profiles: dev
  # kafka:
  #  template:
  #   default-topic: ogriUser-events
  # producer:
  #  bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  #  key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
  #  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #  properties:
  #   acks: all
  #   retries: 10
  #   retry.backoff.ms: 1000
  # admin:
  #   properties:
  #    bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive-app
  application:
    name: REACTIVE-APP
server:
  port: 8084


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"






#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        registerHealthIndicator: true
#        slidingWindowSize: 10
#        minimumNumberOfCalls: 5
#        permittedNumberOfCallsInHalfOpenState: 3
#        automaticTransitionFromOpenToHalfOpenEnabled: true
#        waitDurationInOpenState: 5s
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10
#        recordExceptions:
#          - org.springframework.web.client.HttpServerErrorException
#          - java.util.concurrent.TimeoutException
#          - java.io.IOException
#    instances:
#      service1:
#        registerHealthIndicator: true
#        ringBufferSizeInClosedState: 10
#        ringBufferSizeInHalfOpenState: 3
#        waitDurationInOpenState: PT50S
#        failureRateThreshold: 50
#        eventConsumerBufferSize: 10
#
#
#
graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true

actionbean:
  enabled: false

---

spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive-app
  application:
    name: REACTIVE-APP
server:
  port: 8084


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true