spring:
  #  profiles: dev
  # kafka:
  #  template:
  #   default-topic: ogriUser-events
  # producer:
  #  bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
  #  key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
  #  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  #  properties:
  #   acks: all
  #   retries: 10
  #   retry.backoff.ms: 1000
  # admin:
  #   properties:
  #    bootstrap.servers: localhost:9092,localhost:9093,localhost:9094
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive-app
  application:
    name: REACTIVE-APP
server:
  port: 8084


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost



resilience4j:
  circuitbreaker:
    instances:
      reactiveService:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      reactiveService:
        maxRetryAttempts: 5
        waitDuration: 10s


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always




graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    # Enable or disable the introspection query. Disabling it puts your server in contravention of the GraphQL
    # specification and expectations of most clients, so use this option with caution
    introspection-enabled: true

actionbean:
  enabled: false

---

spring:
  profiles: prod
  data:
    mongodb:
      host: localhost
      port: 27017
      database: reactive-app
  application:
    name: REACTIVE-APP
server:
  port: 8084


eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

management:
  endpoints:
    web:
      exposure:
        include: "*"

graphql:
  servlet:
    mapping: /graphql
    enabled: true
    corsEnabled: false
    exception-handlers-enabled: true
  tools:
    schema-location-pattern: "**/*.graphqls"
    introspection-enabled: true