server:
  port: 8087

spring:
  application:
    name: resilience-service

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      resilience-Service:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 4
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED


  retry:
    instances:
      resilience-Service:
        maxRetryAttempts: 4
        waitDuration: 10s