spring:
  application:
    name: eureka-server

server:
  port: 8761


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    service-url:
        defaultZone: http://localhost:8761/eureka


